version: '3'
services: 
    tac-web-debug: # times-are-changing (tac)
        build:
            context: '.'
            dockerfile: debug.dockerfile
        volumes:
            - .:/home/${USER}/my/projects/times-are-changing
        ports:
            - ${PORT}:${PORT}
            - 9229:9229
        env_file: .env