query getUsersPage($params: UserPaginationInput!) {
    getUsersPage(params: $params) {
        total
        data {
            role
            name
            login
            avatarImgId: avatarImgIdOrDefault
            creationDate
        }
    }
}