fragment PagedUser on User {
    role
    name
    login
    avatarImgId: avatarImgIdOrDefault
    creationDate
}


query getUsersPage($params: UserPaginationInput!) {
    getUsersPage(params: $params) {
        total
        data { ...PagedUser }
    }
}