fragment EntireUser on User {
    __typename
    creationDate
    lastUpdateDate
    role
    name
    login
    avatarImgId: avatarImgIdOrDefault
}

fragment EntireClientAndToken on UserAndToken {
    token
    client: user { ...EntireUser }
}

query getMe {
    getMe { ...EntireUser }
}

mutation signUp($params: SignUpInput!) {
    signUp(params: $params) { ...EntireClientAndToken }
}

mutation signIn($params: SignInInput!) {
    signIn(params: $params) { ...EntireClientAndToken }
}